#!/usr/bin/env bash
brew install --cask dropbox
brew install --cask firefox
brew install --cask flycut
brew install --cask google-chrome
brew install --cask iterm2
brew install --cask java
brew install --cask mat
brew install --cask skype
brew install --cask slack
brew install --cask spotify
brew install --cask sublime-text
brew install --cask tunnelblick
brew install --cask vagrant
brew install --cask virtualbox
brew install --cask vlc
brew install --cask whatsapp
brew install --cask docker
brew install --cask jetbrains-toolbox
