#!/usr/bin/env bash
brew cask install dropbox
brew cask install firefox
brew cask install flycut
brew cask install google-chrome
brew cask install iterm2
brew cask install java
brew cask install mat
brew cask install skype
brew cask install slack
brew cask install spotify
brew cask install sublime-text
brew cask install tunnelblick
brew cask install vagrant
brew cask install virtualbox
brew cask install vlc
brew cask install whatsapp
brew cask install docker
brew cask install jetbrains-toolbox
